function pageSet(prefix, count, title, note) {
  return Array.from({ length: count }, (_, index) => {
    const page = index + 1;
    return {
      id: `${prefix}-${page}`,
      src: `/media/${prefix}-${page}.jpg`,
      brand: "files",
      year: String(page),
      title: {
        ar: `${title.ar} — ${page}`,
        en: `${title.en} — ${page}`,
      },
      note,
    };
  });
}

export const works = [
  {
    id: "kayan-bottle",
    src: "/media/kayan-bottle.jpg",
    brand: "kayan",
    year: "95",
    title: {
      ar: "كيان — اليوم الوطني",
      en: "Kayan — National Day",
    },
    note: {
      ar: "عطر في قلب هوية اليوم الوطني السعودي 95.",
      en: "A fragrance framed inside Saudi National Day 95.",
    },
  },
  {
    id: "kayan-presence",
    src: "/media/kayan-presence.jpg",
    brand: "kayan",
    year: "95",
    title: {
      ar: "كيان — حضور لا يُنسى",
      en: "Kayan — Unforgettable presence",
    },
    note: {
      ar: "إعلان صورة يربط العطر بالحضور الشخصي.",
      en: "A portrait ad that ties scent to presence.",
    },
  },
  {
    id: "kayan-musk",
    src: "/media/kayan-musk.jpg",
    brand: "kayan",
    year: "95",
    title: {
      ar: "كيان — مسك",
      en: "Kayan — Musk",
    },
    note: {
      ar: "بوست منتج بزخرفة خليجية وحركة ضوء.",
      en: "A product post with Gulf ornament and light motion.",
    },
  },
  {
    id: "kayan-oud",
    src: "/media/kayan-oud.jpg",
    brand: "kayan",
    year: "95",
    title: {
      ar: "كيان — عطر بخور",
      en: "Kayan — Bakhoor",
    },
    note: {
      ar: "حملة بخور بهوية خضراء وخط عربي واسع.",
      en: "A bakhoor campaign in green with wide Arabic type.",
    },
  },
  {
    id: "capital-puzzle",
    src: "/media/capital-puzzle.jpg",
    brand: "capital",
    year: "2025",
    title: {
      ar: "Capital — إدارة المشروعات",
      en: "Capital — Project management",
    },
    note: {
      ar: "شرح بصري لتمويل وإدارة الشركات الصغيرة.",
      en: "A visual explainer for SME finance and management.",
    },
  },
  {
    id: "capital-growth",
    src: "/media/capital-growth.jpg",
    brand: "capital",
    year: "2025",
    title: {
      ar: "Capital — نمو واستثمار",
      en: "Capital — Growth and investment",
    },
    note: {
      ar: "إعلان يحوّل التردد إلى قرار تسجيل.",
      en: "An ad that turns hesitation into a signup.",
    },
  },
  {
    id: "capital-reward",
    src: "/media/capital-reward.jpg",
    brand: "capital",
    year: "2025",
    title: {
      ar: "Capital — اربح معنا",
      en: "Capital — Earn with us",
    },
    note: {
      ar: "عرض 500 جنيه داخل مشهد تمويل وبناء.",
      en: "A 500 EGP offer staged with finance and building.",
    },
  },
  {
    id: "capital-services",
    src: "/media/capital-services.jpg",
    brand: "capital",
    year: "2025",
    title: {
      ar: "Capital — ثلاث خدمات",
      en: "Capital — Three services",
    },
    note: {
      ar: "استثمار، تمويل، وإدارة مشروعات في لوحة واحدة.",
      en: "Investment, finance, and project management on one board.",
    },
  },
  {
    id: "desi-web",
    src: "/media/desi-web.jpg",
    brand: "desi",
    year: "2025",
    title: {
      ar: "ديزين — واجهة المتجر",
      en: "Desi25 — Storefront UI",
    },
    note: {
      ar: "عرض تصميم متجر إلكتروني على شاشة لابتوب.",
      en: "An ecommerce interface presented on a laptop.",
    },
  },
  {
    id: "desi-services",
    src: "/media/desi-services.jpg",
    brand: "desi",
    year: "2025",
    title: {
      ar: "ديزين — الخدمات",
      en: "Desi25 — Services",
    },
    note: {
      ar: "تصميم متاجر، دعم فني، وتحليل بيانات.",
      en: "Store design, technical support, and site analytics.",
    },
  },
  {
    id: "desi-store",
    src: "/media/desi-store.jpg",
    brand: "desi",
    year: "2025",
    title: {
      ar: "ديزين — ألوان المتجر",
      en: "Desi25 — Store colors",
    },
    note: {
      ar: "رسالة بصرية عن الألوان التي تجذب العميل.",
      en: "A visual argument for colors that pull customers in.",
    },
  },
  {
    id: "desi-apps",
    src: "/media/desi-apps.jpg",
    brand: "desi",
    year: "95",
    title: {
      ar: "ديزين — عروض اليوم الوطني",
      en: "Desi25 — National Day offers",
    },
    note: {
      ar: "حملة تطبيقات بهوية اليوم الوطني.",
      en: "An app campaign dressed for National Day.",
    },
  },
  {
    id: "desi-packages",
    src: "/media/desi-packages.jpg",
    brand: "desi",
    year: "2025",
    title: {
      ar: "ديزين — الباقات",
      en: "Desi25 — Packages",
    },
    note: {
      ar: "استعراض باقات المنتج على شاشات متتابعة.",
      en: "Product packages shown across a sequence of screens.",
    },
  },
  {
    id: "desi-ai",
    src: "/media/desi-ai.jpg",
    brand: "desi",
    year: "2025",
    title: {
      ar: "ديزين — أتمتة الذكاء الاصطناعي",
      en: "Desi25 — AI automation",
    },
    note: {
      ar: "بوست تقني يشرح الأتمتة بلغة بصرية.",
      en: "A technical post that explains automation visually.",
    },
  },
  {
    id: "desi-privacy",
    src: "/media/desi-privacy.jpg",
    brand: "desi",
    year: "2025",
    title: {
      ar: "ديزين — سياسة الخصوصية",
      en: "Desi25 — Privacy policy",
    },
    note: {
      ar: "تبسيط الثقة والأمان في بيانات المستخدم.",
      en: "Trust and data safety, simplified.",
    },
  },
  {
    id: "desi-eid",
    src: "/media/desi-eid.jpg",
    brand: "desi",
    year: "2026",
    title: {
      ar: "ديزين — عيد فطر",
      en: "Desi25 — Eid",
    },
    note: {
      ar: "تهنئة عيد بهلال متحرك الهوية.",
      en: "An Eid greeting built around a crescent.",
    },
  },
  {
    id: "desi-ramadan",
    src: "/media/desi-ramadan.jpg",
    brand: "desi",
    year: "2026",
    title: {
      ar: "ديزين — رمضان",
      en: "Desi25 — Ramadan",
    },
    note: {
      ar: "بوست رمضاني بخط عربي طويل وفوانيس.",
      en: "A Ramadan post with tall Arabic type and lanterns.",
    },
  },
  {
    id: "desi-offers",
    src: "/media/desi-offers.jpg",
    brand: "desi",
    year: "95",
    title: {
      ar: "ديزين — عروض اليوم",
      en: "Desi25 — Offers of the day",
    },
    note: {
      ar: "بوست عروض اليوم الوطني مع دعوة لزيارة الموقع.",
      en: "A National Day offers post with a prompt to visit the site.",
    },
  },
  {
    id: "desi-campaign",
    src: "/media/desi-campaign.jpg",
    brand: "desi",
    year: "2025",
    title: {
      ar: "ديزين — إعلان الحملة",
      en: "Desi25 — Campaign announcement",
    },
    note: {
      ar: "إعلان حملة الشركة في الرياض، 8 أغسطس 2025.",
      en: "Campaign announcement for the company in Riyadh, 8 August 2025.",
    },
  },
  ...pageSet("hunter", 6, {
    ar: "صياد العملاء في صحراء الخليج",
    en: "Client hunter in the Gulf desert",
  }, {
    ar: "صفحة من ملف الكاروسيل.",
    en: "A page from the carousel file.",
  }),
  ...pageSet("steps", 8, {
    ar: "خطوات بناء الخطة التسويقية",
    en: "Steps to build a marketing plan",
  }, {
    ar: "صفحة من ملف الخطوات.",
    en: "A page from the steps file.",
  }),
]

export const copy = {
  ar: {
    dir: "rtl",
    htmlLang: "ar",
    title: "أحمد عماد — مسوّق رقمي",
    ghost: "صيد",
    nav: [
      { href: "#about", label: "عني" },
      { href: "#experience", label: "الخبرة" },
      { href: "#work", label: "الأعمال" },
      { href: "#plan", label: "الخطة" },
      { href: "#contact", label: "تواصل" },
    ],
    menu: "القائمة",
    close: "إغلاق",
    live: "متاح للتعاون",
    kicker: "مسوّق رقمي · مبيعات شركات",
    name: "أحمد عماد",
    roles: ["صيّاد عملاء", "كاتب خطط نمو", "مدير حسابات", "بائع يقرأ السلوك"],
    lead: "أحوّل تردد العميل إلى رسالة واضحة، وخطة زمنية، وصفقة تتقفل.",
    ctaWork: "شوف الأعمال",
    ctaTalk: "ابدأ محادثة",
    scroll: "الإشارة تتحرك",
    marquee: [
      "علم النفس",
      "مبيعات B2B",
      "خطط 6 أشهر",
      "بريد تسويقي",
      "حملات خليجية",
      "إدارة حسابات",
      "توليد عملاء",
      "تفاوض وإغلاق",
    ],
    aboutKicker: "01 — الإشارة",
    aboutTitle: "أبيع بعد ما أفهم ليه العميل بيسكت.",
    aboutBody:
      "أحمد عماد صبحي مدين، من مدينة السادات. خريج آداب علم نفس، واشتغلت مبيعات شركات من 2022: أولًا حلول ويب وبرمجيات مع فوندا، وبعدين حسابات لوجستية مع سيلا للتوصيل. الخيط واحد في الاتنين — القرار مش بيتحصل من عرض السعر، بيحصل لما الرسالة تلمس السبب الحقيقي للتردد.",
    facts: [
      { k: "المكان", v: "شبين الكوم، مصر" },
      { k: "اللغات", v: "العربية · English" },
      { k: "الخبرة", v: "أكتر من 3 سنين" },
      { k: "القطاعات", v: "لوجستيات · برمجيات" },
    ],
    quote: "هنا لا يكفي المنتج القوي.",
    quoteBy: "من سلسلة «صياد العملاء في صحراء الخليج»",
    expKicker: "02 — المسار",
    expTitle: "شغل حقيقي على الحساب والصفقة.",
    jobs: [
      {
        years: "2024 — 2025",
        role: "مندوب مبيعات شركات / مدير حسابات",
        org: "Sella Delivery Services",
        points: [
          "استهداف شركاء وعملاء جدد في قطاع التوصيل واللوجستيات.",
          "إدارة الحسابات والاحتفاظ بالعميل على المدى الطويل.",
          "عروض أسعار مخصصة، عرض الحل، والتفاوض لحد الإغلاق.",
          "متابعة السوق والمنافسين، وتقارير الأداء على أدوات أوفيس.",
        ],
      },
      {
        years: "2022 — 2023",
        role: "أخصائي مبيعات / تطوير أعمال",
        org: "Fonda Web Software Solutions",
        points: [
          "توليد عملاء مؤهلين لحلول الويب والبرمجيات عند الشركات الصغيرة والمتوسطة.",
          "عروض تقديمية توضّح قيمة الحل الرقمي لصاحب القرار.",
          "دورة البيع كاملة: تواصل بارد، عرض، إغلاق، ثم تسليم للفريق التقني.",
          "بناء شبكة علاقات تغذي البيع الوارد والصادر.",
        ],
      },
    ],
    edu: "بكالوريوس آداب — علم النفس",
    eduNote: "سلوك، تواصل، وإقناع. ده الأساس اللي بتتبني عليه الرسالة البيعية.",
    skillKicker: "الأدوات",
    skills: [
      "مبيعات B2B",
      "توليد عملاء",
      "إدارة حسابات",
      "تفاوض العقود",
      "إغلاق الصفقات",
      "بحث سوق",
      "CRM",
      "Microsoft Office",
      "تسويق بالبريد",
      "محتوى سوشيال",
      "خطط حملات",
      "علم النفس البيعي",
    ],
    storyKicker: "03 — الطريقة",
    storyTitle: "ثلاث إشارات قبل ما الإعلان يصرف فلوس.",
    storyLead:
      "في سلسلة «صياد العملاء في صحراء الخليج» يوسف في الرياض بيتفرج على لوحة المنافسين. المنتج الأقوى خسر. الكسبان فهم النفس. الاستراتيجيات التلاتة:",
    strategies: [
      {
        n: "01",
        name: "الإثبات الاجتماعي",
        text: "بدل «نحن الأفضل»، حط دليل قريب: أربع شركات خليجية اختارتنا هذا الأسبوع.",
      },
      {
        n: "02",
        name: "الالتزام الصغير",
        text: "اطلب خطوة رخيصة نفسيًا — ورقة بيضاء مجانية — وبعد التحميل يبقى العميل جاهز يسمع العرض.",
      },
      {
        n: "03",
        name: "الندرة الاجتماعية",
        text: "عدد محدود في مكان محدد: ثلاث باقات للشركات في الرياض، وتختفي خلال يومين.",
      },
    ],
    stepsTitle: "وبعدين الخطة، مش الإعلان العشوائي.",
    steps: [
      { n: "١", t: "حدد العميل", d: "مش كل الناس. فئة محتاجة المنتج فعلًا." },
      { n: "٢", t: "اكتب الحل", d: "الرسالة بتجاوب: إزاي المنتج بيشيل المشكلة؟" },
      { n: "٣", t: "اختَر المكان", d: "فين العميل بيقضي وقته، مش فين الزحمة أكبر." },
      { n: "٤", t: "اجمع وتابع", d: "الإعلان الناجح بيبني قائمة، مش بيبيع من أول ظهور." },
      { n: "٥", t: "قلّل الاختيار", d: "خيارين واضحين أحسن من قائمة بتوقف القرار." },
      { n: "٦", t: "سهّل التجربة", d: "جرّب قبل الشراء، وادفع من غير عوائق." },
    ],
    workKicker: "04 — الأعمال",
    workTitle: "حملات اتبنت عشان تتساب في الذاكرة.",
    workLead: "تصاميم كيان وCapital وديزين، وملفات الكاروسيل وخطة Trading PRO.",
    filters: [
      { id: "all", label: "الكل" },
      { id: "kayan", label: "كيان" },
      { id: "capital", label: "Capital" },
      { id: "desi", label: "ديزين" },
      { id: "files", label: "الملفات" },
    ],
    openWork: "تكبير",
    planKicker: "05 — الخطة",
    planTitle: "Trading PRO — خارطة ستة أشهر.",
    planLead:
      "خطة تسويق 2026 لمنصة تداول. الجمهور متقسم، والزمن متقسم، والأتمتة شغالة من أول يوم.",
    segmentsLabel: "تقسيم السوق",
    segments: [
      { name: "متداولو اليوم", text: "سيولة عالية وأسهم وكريبتو. يهمهم سرعة التنفيذ وأدوات التحليل." },
      { name: "المستثمر الاستراتيجي", text: "طاقة وأسهم قيادية. يعيش على التقارير والتوقعات الطويلة." },
      { name: "المبتدئ الحذر", text: "محتاج تعليم، نسخ صفقات، وحساب تجريبي قبل ما يحط فلوس." },
      { name: "متداول الخوارزميات", text: "APIs واستقرار وزمن استجابة منخفض." },
    ],
    phases: [
      {
        name: "الثقة",
        when: "الشهر 1–2",
        text: "حملة Trade Like a PRO: الترخيص، الأمان، وسلاسة الإيداع والسحب. وبعدها ويبينار أسبوعي عن طاقة المستقبل ونظرة الكريبتو 2026.",
      },
      {
        name: "الاكتساب",
        when: "الشهر 3–4",
        text: "إعلانات بحث وسوشيال على كلمات نية عالية، ثم برنامج إحالة متدرج يخفض تكلفة اكتساب العميل.",
      },
      {
        name: "الولاء",
        when: "الشهر 5–6",
        text: "بوتات تداول وميزات جديدة لرفع التفاعل، ثم إعادة استهداف لمن سجّل ولم يودع.",
      },
    ],
    autoLabel: "الأتمتة داخل الخطة",
    autos: [
      "تنبيهات سعر حسب قائمة مراقبة كل مستخدم.",
      "رحلة ترحيب فيها فيديو وأول صفقة موجّهة.",
      "دعم آلي على مدار الساعة لأسئلة المنصة وبيانات السوق.",
    ],
    targetsLabel: "أهداف الستة أشهر — مش نتائج محققة",
    targets: [
      { v: "−15%", l: "تكلفة اكتساب العميل" },
      { v: "5%", l: "زائر يتحول لمودع نشط" },
      { v: "+20%", l: "قيمة العميل عبر الأصول" },
      { v: "+10%", l: "نمو المستخدم النشط شهريًا" },
    ],
    proofKicker: "06 — البريد",
    proofTitle: "تقرير حملة بريدية.",
    proofLead: "المعدلات الظاهرة في تقرير Mailchimp المرفق مع الملف.",
    metrics: [
      { v: "50%", l: "معدل الفتح" },
      { v: "2.11%", l: "معدل النقر" },
      { v: "0.33%", l: "الارتداد" },
      { v: "0%", l: "إلغاء الاشتراك" },
      { v: "99.58%", l: "تسليم ناجح" },
    ],
    contactKicker: "07 — التردد",
    contactTitle: "لو عندك عميل بيتأخر في القرار، ابعت التفاصيل.",
    contactLead: "شبين الكوم. أرد خلال يوم عمل.",
    email: "reu3758@gmail.com",
    phone: "0109 473 1657",
    phoneHref: "tel:+201094731657",
    mailHref: "mailto:reu3758@gmail.com",
    waHref: "https://wa.me/201094731657",
    wa: "واتساب",
    call: "اتصال",
    mail: "إيميل",
    foot: "أحمد عماد صبحي مدين",
    footNote: "مسوّق رقمي ومبيعات شركات",
  },
  en: {
    dir: "ltr",
    htmlLang: "en",
    title: "Ahmed Emad — Digital Marketer",
    ghost: "HUNT",
    nav: [
      { href: "#about", label: "About" },
      { href: "#experience", label: "Experience" },
      { href: "#work", label: "Work" },
      { href: "#plan", label: "Plan" },
      { href: "#contact", label: "Contact" },
    ],
    menu: "Menu",
    close: "Close",
    live: "Open for work",
    kicker: "Digital marketer · B2B sales",
    name: "Ahmed Emad",
    roles: ["Client hunter", "Growth-plan writer", "Account manager", "Sales shaped by psychology"],
    lead: "I turn a hesitant buyer into a clear message, a timed plan, and a closed deal.",
    ctaWork: "See the work",
    ctaTalk: "Start a conversation",
    scroll: "Signal in motion",
    marquee: [
      "Psychology",
      "B2B sales",
      "6-month plans",
      "Email marketing",
      "Gulf campaigns",
      "Account care",
      "Lead generation",
      "Negotiation",
    ],
    aboutKicker: "01 — Signal",
    aboutTitle: "I sell after I understand why the client goes quiet.",
    aboutBody:
      "Ahmed Emad Sobhi Madian, based in Sadat City. A psychology graduate who has worked B2B sales since 2022 — first web and software solutions at Fonda, then logistics accounts at Sella Delivery. The thread is the same: the deal is not won by the price sheet. It is won when the message touches the real reason for hesitation.",
    facts: [
      { k: "Base", v: "Shibin El Kom, Egypt" },
      { k: "Languages", v: "Arabic · English" },
      { k: "Practice", v: "3+ years" },
      { k: "Sectors", v: "Logistics · Software" },
    ],
    quote: "A strong product is not enough here.",
    quoteBy: "From the series “Client Hunter in the Gulf Desert”",
    expKicker: "02 — Path",
    expTitle: "Real work on the account and the deal.",
    jobs: [
      {
        years: "2024 — 2025",
        role: "B2B Sales Representative / Account Manager",
        org: "Sella Delivery Services",
        points: [
          "Found and signed corporate clients and partners in delivery and logistics.",
          "Managed accounts with an eye on retention, not a one-off order.",
          "Custom proposals, solution presentations, and negotiation through to close.",
          "Watched the market and competitors, and reported performance in Microsoft Office.",
        ],
      },
      {
        years: "2022 — 2023",
        role: "Sales Specialist / Business Development",
        org: "Fonda Web Software Solutions",
        points: [
          "Generated qualified leads for web and software among small and medium companies.",
          "Ran demonstrations that made the digital product legible to decision-makers.",
          "Owned the cycle from cold outreach to close, then handed a clear brief to the technical team.",
          "Kept a living network for inbound and outbound opportunities.",
        ],
      },
    ],
    edu: "Bachelor of Arts — Psychology",
    eduNote: "Behavior, communication, and persuasion. That is the floor under the sales message.",
    skillKicker: "Tools",
    skills: [
      "B2B sales",
      "Lead generation",
      "Account management",
      "Contract negotiation",
      "Closing",
      "Market research",
      "CRM",
      "Microsoft Office",
      "Email marketing",
      "Social content",
      "Campaign plans",
      "Sales psychology",
    ],
    storyKicker: "03 — Method",
    storyTitle: "Three signals before an ad spends money.",
    storyLead:
      "In “Client Hunter in the Gulf Desert,” Yusuf in Riyadh watches a competitor’s dashboard. The stronger product lost. The winner understood people. Three moves:",
    strategies: [
      {
        n: "01",
        name: "Social proof",
        text: "Instead of “we are the best,” place a near proof: four Gulf companies chose us this week.",
      },
      {
        n: "02",
        name: "Micro-commitment",
        text: "Ask for a cheap step — a free white paper. After the download, the client is ready to hear the offer.",
      },
      {
        n: "03",
        name: "Social scarcity",
        text: "A small number in a specific place: three packages for companies in Riyadh, gone within two days.",
      },
    ],
    stepsTitle: "Then a plan, not a random ad.",
    steps: [
      { n: "1", t: "Name the client", d: "Not everyone. A group that actually needs the product." },
      { n: "2", t: "Write the fix", d: "The message answers how the product removes the problem." },
      { n: "3", t: "Pick the place", d: "Where the client spends time, not where the crowd is loudest." },
      { n: "4", t: "Collect and follow", d: "A working ad builds a list. It does not sell on the first glance." },
      { n: "5", t: "Cut the choices", d: "Two clear options beat a menu that freezes the decision." },
      { n: "6", t: "Ease the trial", d: "Let them try before they buy, and pay without friction." },
    ],
    workKicker: "04 — Work",
    workTitle: "Campaigns built to stay in memory.",
    workLead: "Kayan, Capital, and Desi25 designs, plus the carousel files and the Trading PRO plan.",
    filters: [
      { id: "all", label: "All" },
      { id: "kayan", label: "Kayan" },
      { id: "capital", label: "Capital" },
      { id: "desi", label: "Desi25" },
      { id: "files", label: "Files" },
    ],
    openWork: "Enlarge",
    planKicker: "05 — Plan",
    planTitle: "Trading PRO — a six-month map.",
    planLead:
      "A 2026 marketing plan for a trading platform. The audience is split, the time is split, and automation starts on day one.",
    segmentsLabel: "Market split",
    segments: [
      { name: "Day traders", text: "High-liquidity stocks and crypto. They care about speed and analysis tools." },
      { name: "Strategic investors", text: "Energy and blue chips. They live on reports and long forecasts." },
      { name: "Cautious beginners", text: "They need education, copy-trading, and a demo before they fund an account." },
      { name: "Algo traders", text: "APIs, stability, and low latency." },
    ],
    phases: [
      {
        name: "Trust",
        when: "Months 1–2",
        text: "The Trade Like a PRO campaign: licensing, security, and clean deposits and withdrawals. Then a weekly webinar on the future of energy and the 2026 crypto outlook.",
      },
      {
        name: "Acquisition",
        when: "Months 3–4",
        text: "Search and social ads on high-intent phrases, then a tiered referral program that lowers acquisition cost.",
      },
      {
        name: "Loyalty",
        when: "Months 5–6",
        text: "Trading bots and new features to lift engagement, then retargeting for people who registered and never deposited.",
      },
    ],
    autoLabel: "Automation inside the plan",
    autos: [
      "Price alerts based on each user’s watchlist.",
      "An onboarding path with video and a guided first trade.",
      "Round-the-clock automated support for platform questions and market data.",
    ],
    targetsLabel: "Six-month targets — not claimed results",
    targets: [
      { v: "−15%", l: "Customer acquisition cost" },
      { v: "5%", l: "Visitor to active depositor" },
      { v: "+20%", l: "Lifetime value across assets" },
      { v: "+10%", l: "Monthly active user growth" },
    ],
    proofKicker: "06 — Email",
    proofTitle: "An email campaign report.",
    proofLead: "Rates shown on the attached Mailchimp report.",
    metrics: [
      { v: "50%", l: "Open rate" },
      { v: "2.11%", l: "Click rate" },
      { v: "0.33%", l: "Bounce rate" },
      { v: "0%", l: "Unsubscribe" },
      { v: "99.58%", l: "Successful delivery" },
    ],
    contactKicker: "07 — Frequency",
    contactTitle: "If a client is slow to decide, send the details.",
    contactLead: "Shibin El Kom. I reply within one working day.",
    email: "reu3758@gmail.com",
    phone: "0109 473 1657",
    phoneHref: "tel:+201094731657",
    mailHref: "mailto:reu3758@gmail.com",
    waHref: "https://wa.me/201094731657",
    wa: "WhatsApp",
    call: "Call",
    mail: "Email",
    foot: "Ahmed Emad Sobhi Madian",
    footNote: "Digital marketer and B2B sales",
  },
}
